### ISSUE TITLE
Plugin does not work when no folder is open

### ISSUE THREAD

**Issue by krzyk240** [pfultz2/ClangComplete#29]
When I open C++ file in sublime with no opened folders, plugin doesn't work and I see folowind log in console:
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 403, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "/home/quasar/.config/sublime-text-3/Packages/ClangComplete/clangcomplete.py", line 492, in on_post_text_command
    self.complete_at(view, "", pos, 0)
  File "/home/quasar/.config/sublime-text-3/Packages/ClangComplete/clangcomplete.py", line 448, in complete_at
    completions = convert_completions(get_completions(filename, get_args(view), row+1, col+1, "", timeout, get_unsaved_buffer(view)))
  File "/home/quasar/.config/sublime-text-3/Packages/ClangComplete/clangcomplete.py", line 124, in get_args
    project_path = get_project_path(view)
  File "/home/quasar/.config/sublime-text-3/Packages/ClangComplete/clangcomplete.py", line 23, in get_project_path
    return view.window().folders()[0]
IndexError: list index out of range

**Comment by pfultz2** [comment]
Hmm, so I wonder what `get_project_path` can return if there is no folders.
